In [3]:
import pandas as pd
df = pd.read_csv("./data/sales.csv", usecols=['订单号', '产品类别', '产品名称', '销售数量', '单价'])
df['销售额'] = df['销售数量'] * df['单价']
df.to_csv('./data/sales_output.csv', index=False)

In [15]:
import pandas as pd
df = pd.read_csv("./data/sales.csv", usecols=['订单号', '产品类别', '产品名称', '销售数量', '单价'])
df.head()

df.tail()

df.describe()

# df.info()

# df[['订单号','产品类别']]

# df.iloc[:10:2]

df.loc[:10:2]

           订单号  产品类别  产品名称  销售数量   单价
0   6805677496  家居用品    枕头    10  199
2   5888085059  电子产品  智能音箱     5  399
4   6801664364    食品    薯片     2   19
6   6857752388    服装    袜子     7  -29
8   5875402232  电子产品   路由器     9  299
10  5808071569    食品   矿泉水     9   29

In [33]:
import pandas as pd
df = pd.read_csv("./data/sales.csv")

# 判断每个单元格是否为空(返回布尔值)
df.isnull()

# 删除含有缺失的行或列
# df.dropna(inplace=True)

# 用指定值填充缺失值
# df.fillna("--")

# 用前一行的值填充当前缺失值
# df.ffill(inplace=True)

# 用后一行的值填充当前缺失值
# df.bfill(inplace=True)

# 标记哪些行是重复的
# df[df.duplicated("订单号")]

# 删除重复行
# df.drop_duplicates(subset='订单号', inplace=True)

# 绝对值化
# df['单价'] = df['单价'].abs()

# 字符串替换 统一日期或分隔符格式
df['订单日期'] = df['订单日期'].str.replace("/", "-")
df

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3    6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19    NaN  微信支付  2025-06-02
..          ...   ...   ...   ...  ...    ...   ...         ...
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89     西安   银行卡  2026-03-20

[1000 rows x 8 columns]

In [40]:
import pandas as pd
df = pd.read_csv("./data/sales.csv")
df['销售额'] = df['销售数量'] * df['单价']

df.groupby('产品类别')['销售额'].sum()

df.groupby('产品类别')['销售额'].count()

df.groupby('产品类别')['销售额'].max()
df.groupby('产品类别')['销售额'].min()
df.groupby('产品类别')['销售额'].mean()

df.groupby('产品类别').agg({'销售数量': 'sum', '销售额': 'sum', '单价': 'mean'})

      销售数量     销售额          单价
产品类别
图书    1076   68614   65.263736
家居用品  1121  741049  686.644231
服装    1080  334004  313.103627
电子产品  1137  935983  776.073171
食品    1125   73555   65.698113

In [43]:
import pandas as pd
df = pd.read_csv("./data/sales.csv", usecols=['订单号', '产品类别', '产品名称', '销售数量', '单价'], nrows=30)
# 单列排序  False为降序
# df = df.sort_values(by="销售数量", ascending=False)

# 先按照 销售数量降序排序 如果销售数量相同 单价升序排序
df = df.sort_values(by=["销售数量", "单价"], ascending=[False, True])
df

           订单号  产品类别  产品名称  销售数量    单价
20  6893087111    食品    蜂蜜    10    89
0   6805677496  家居用品    枕头    10   199
11  6890234923  家居用品  餐具套装    10   199
14  5804178086  电子产品  蓝牙耳机    10   199
19  5852807025    服装    毛衣    10   399
10  5808071569    食品   矿泉水     9    29
26  5854211330    食品    果干     9    59
8   5875402232  电子产品   路由器     9   299
22  5894724625  电子产品  智能手机     9  2999
13  6880065056    图书   练习册     8    39
23  6867258691    服装    围巾     8   129
24  5875023454  电子产品  智能手机     8  2999
6   6857752388    服装    袜子     7   -29
17  5835623429    图书    食谱     6    49
18  5852698441  家居用品    蜡烛     6    49
7   6898807429    服装    T恤     6   199
27  5840958148    服装    衬衫     6   299
1   5857234132    食品    海苔     5    29
15  5878551159    图书   练习册     5    39
21  5871374068    图书   摄影集     5   129
2   5888085059  电子产品  智能音箱     5   399
5   5897064217    图书    字帖     4    29
29  5816896128    食品    咖啡     4   129
3   6823473137    食品    面包     3    29
12  5891597362  电子产品    鼠标     3    89
25  6837065480    服装    毛衣     3   399
4   6801664364    食品    薯片     2    19
16  5812573980    食品    坚果     2    79
9   5888085066    图书    字典     2    99
28  6842052369  家居用品    扫把     1    39